//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models.RRHHEmployee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RRHH_EmployeeEntities : DbContext
    {
        public DB_RRHH_EmployeeEntities()
            : base("name=DB_RRHH_EmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_RRHH_Employee> DB_RRHH_Employee { get; set; }
        public virtual DbSet<DB_RRHH_History> DB_RRHH_History { get; set; }
        public virtual DbSet<Direction> Directions { get; set; }
        //public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
