//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models.RRHHEmployee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direction
    {
        public int ID_User { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string URL_Google_Maps { get; set; }
        public string Description { get; set; }
    
        public virtual DB_RRHH_Employee DB_RRHH_Employee { get; set; }
    }
}
