//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models.SAS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SAS_2019Entities : DbContext
    {
        public SAS_2019Entities()
            : base("name=SAS_2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_Client> DB_Client { get; set; }
        public virtual DbSet<DB_RRHH_Employee> DB_RRHH_Employee { get; set; }
        public virtual DbSet<Employee_Ticket> Employee_Ticket { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Ticket_Attachments> Ticket_Attachments { get; set; }
        public virtual DbSet<Ticket_History> Ticket_History { get; set; }
        public virtual DbSet<User_Rol> User_Rol { get; set; }
    
        public virtual ObjectResult<SearchByStatusClient_Result> SearchByStatusClient(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchByStatusClient_Result>("SearchByStatusClient", statusParameter);
        }
    
        public virtual ObjectResult<SearchByStatusEmployee_Result> SearchByStatusEmployee(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchByStatusEmployee_Result>("SearchByStatusEmployee", statusParameter);
        }
    
        public virtual int spAddTicket(string username, Nullable<System.DateTime> datein, Nullable<System.DateTime> dateout, string status, string priority, string description, string category, string urlimage, string urldoc, Nullable<System.DateTime> datecreate, ObjectParameter result)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var dateinParameter = datein.HasValue ?
                new ObjectParameter("datein", datein) :
                new ObjectParameter("datein", typeof(System.DateTime));
    
            var dateoutParameter = dateout.HasValue ?
                new ObjectParameter("dateout", dateout) :
                new ObjectParameter("dateout", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var priorityParameter = priority != null ?
                new ObjectParameter("priority", priority) :
                new ObjectParameter("priority", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var urlimageParameter = urlimage != null ?
                new ObjectParameter("urlimage", urlimage) :
                new ObjectParameter("urlimage", typeof(string));
    
            var urldocParameter = urldoc != null ?
                new ObjectParameter("urldoc", urldoc) :
                new ObjectParameter("urldoc", typeof(string));
    
            var datecreateParameter = datecreate.HasValue ?
                new ObjectParameter("datecreate", datecreate) :
                new ObjectParameter("datecreate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddTicket", usernameParameter, dateinParameter, dateoutParameter, statusParameter, priorityParameter, descriptionParameter, categoryParameter, urlimageParameter, urldocParameter, datecreateParameter, result);
        }
    
        public virtual ObjectResult<spLoginByUsernamePassword_Result> spLoginByUsernamePassword(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLoginByUsernamePassword_Result>("spLoginByUsernamePassword", usernameParameter, passwordParameter);
        }
    }
}
