//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models.SAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_History
    {
        public int ID_Ticket { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public Nullable<int> UserUpdate { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual DB_RRHH_Employee DB_RRHH_Employee { get; set; }
        public virtual DB_RRHH_Employee DB_RRHH_Employee1 { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
