//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models.SAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Attachments
    {
        public int ID { get; set; }
        public Nullable<int> ID_Ticket { get; set; }
        public string URL_Image { get; set; }
        public string URL_Doc { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
