//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models.SAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Rol
    {
        public int ID_Employee { get; set; }
        public Nullable<int> ID_Rol { get; set; }
    
        public virtual DB_RRHH_Employee DB_RRHH_Employee { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
