//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RRHH_History
    {
        public int ID_User { get; set; }
        public Nullable<int> User_Update { get; set; }
        public System.DateTime Change_Date { get; set; }
        public Nullable<int> User_Create { get; set; }
        public System.DateTime Date_Create { get; set; }
        public string Description { get; set; }
    
        public virtual DB_RRHH_Employee DB_RRHH_Employee { get; set; }
        public virtual DB_RRHH_Employee DB_RRHH_Employee1 { get; set; }
        public virtual DB_RRHH_Employee DB_RRHH_Employee2 { get; set; }
    }
}
