//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Ticket
    {
        public int ID_Employee { get; set; }
        public int ID_Ticket { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> ID_User_Assign { get; set; }
    
        public virtual DB_Client DB_Client { get; set; }
        public virtual DB_RRHH_Employee DB_RRHH_Employee { get; set; }
        public virtual DB_RRHH_Employee DB_RRHH_Employee1 { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
