//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprise
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date_Create { get; set; }
        public string Description { get; set; }
    
        public virtual Belong_To Belong_To { get; set; }
    }
}
