//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        [Display (Name ="ID")]
        public int id { get; set; }

        [Required (ErrorMessage ="Debe ingresar el nombre de usuario")]
        [Display (Name ="User name")]
        public string username { get; set; }

        [Required(ErrorMessage = "Debe ingresar la contraseña")]
        [Display (Name ="Password")]
        [DataType (DataType.Password)]
        public string password { get; set; }

        public int role_id { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
