//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int ID_Team { get; set; }
        public Nullable<int> ID_User_In_Charge { get; set; }
        public System.DateTime Date_Create { get; set; }
        public System.DateTime Date_Finish { get; set; }
    
        public virtual DB_RRHH_Employee DB_RRHH_Employee { get; set; }
    }
}
